package francisco.simon.core.ui.theme.colors.yellow

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

internal val lightYellowScheme = lightColorScheme(
    primary = yellowPrimaryLight,
    onPrimary = yellowOnPrimaryLight,
    primaryContainer = yellowPrimaryContainerLight,
    onPrimaryContainer = yellowOnPrimaryContainerLight,
    secondary = yellowSecondaryLight,
    onSecondary = yellowOnSecondaryLight,
    secondaryContainer = yellowSecondaryContainerLight,
    onSecondaryContainer = yellowOnSecondaryContainerLight,
    tertiary = yellowTertiaryLight,
    onTertiary = yellowOnTertiaryLight,
    tertiaryContainer = yellowTertiaryContainerLight,
    onTertiaryContainer = yellowOnTertiaryContainerLight,
    error = yellowErrorLight,
    onError = yellowOnErrorLight,
    errorContainer = yellowErrorContainerLight,
    onErrorContainer = yellowOnErrorContainerLight,
    background = yellowBackgroundLight,
    onBackground = yellowOnBackgroundLight,
    surface = yellowSurfaceLight,
    onSurface = yellowOnSurfaceLight,
    surfaceVariant = yellowSurfaceVariantLight,
    onSurfaceVariant = yellowOnSurfaceVariantLight,
    outline = yellowOutlineLight,
    outlineVariant = yellowOutlineVariantLight,
    scrim = yellowScrimLight,
    inverseSurface = yellowInverseSurfaceLight,
    inverseOnSurface = yellowInverseOnSurfaceLight,
    inversePrimary = yellowInversePrimaryLight,
    surfaceDim = yellowSurfaceDimLight,
    surfaceBright = yellowSurfaceBrightLight,
    surfaceContainerLowest = yellowSurfaceContainerLowestLight,
    surfaceContainerLow = yellowSurfaceContainerLowLight,
    surfaceContainer = yellowSurfaceContainerLight,
    surfaceContainerHigh = yellowSurfaceContainerHighLight,
    surfaceContainerHighest = yellowSurfaceContainerHighestLight,
)

internal val darkYellowScheme = darkColorScheme(
    primary = yellowPrimaryDark,
    onPrimary = yellowOnPrimaryDark,
    primaryContainer = yellowPrimaryContainerDark,
    onPrimaryContainer = yellowOnPrimaryContainerDark,
    secondary = yellowSecondaryDark,
    onSecondary = yellowOnSecondaryDark,
    secondaryContainer = yellowSecondaryContainerDark,
    onSecondaryContainer = yellowOnSecondaryContainerDark,
    tertiary = yellowTertiaryDark,
    onTertiary = yellowOnTertiaryDark,
    tertiaryContainer = yellowTertiaryContainerDark,
    onTertiaryContainer = yellowOnTertiaryContainerDark,
    error = yellowErrorDark,
    onError = yellowOnErrorDark,
    errorContainer = yellowErrorContainerDark,
    onErrorContainer = yellowOnErrorContainerDark,
    background = yellowBackgroundDark,
    onBackground = yellowOnBackgroundDark,
    surface = yellowSurfaceDark,
    onSurface = yellowOnSurfaceDark,
    surfaceVariant = yellowSurfaceVariantDark,
    onSurfaceVariant = yellowOnSurfaceVariantDark,
    outline = yellowOutlineDark,
    outlineVariant = yellowOutlineVariantDark,
    scrim = yellowScrimDark,
    inverseSurface = yellowInverseSurfaceDark,
    inverseOnSurface = yellowInverseOnSurfaceDark,
    inversePrimary = yellowInversePrimaryDark,
    surfaceDim = yellowSurfaceDimDark,
    surfaceBright = yellowSurfaceBrightDark,
    surfaceContainerLowest = yellowSurfaceContainerLowestDark,
    surfaceContainerLow = yellowSurfaceContainerLowDark,
    surfaceContainer = yellowSurfaceContainerDark,
    surfaceContainerHigh = yellowSurfaceContainerHighDark,
    surfaceContainerHighest = yellowSurfaceContainerHighestDark,
)
